global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:4317"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "nodejs-app"
    static_configs:
      - targets: ["typescript-express-app:3000"]